const { app, BrowserWindow, ipcMain } = require('electron');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { registerDevices } = require('../electron/devices.cjs');
const { registerPanelWindows } = require('../electron/panel-windows.cjs');
const { registerScriptFiles } = require('../electron/script-files.cjs');
const root=path.resolve(__dirname,'..'), output=path.join(root,'node_modules/.tmp/device-review');
fs.mkdirSync(output,{recursive:true});
app.setPath('userData',path.join(output,'profile'));
app.commandLine.appendSwitch('disable-gpu');
let devices;
const timeout=setTimeout(()=>{console.error('Device UI test timeout');app.exit(1);},45000);
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function until(action,label) {for(let i=0;i<150;i++){if(await action())return;await delay(40);}throw new Error(label);}
const js=(window,code)=>window.webContents.executeJavaScript(code,true).catch(error=>{throw new Error(code+'\n'+error.message);});
app.whenReady().then(async()=>{
  ipcMain.handle('app:metadata',()=>({name:'Auto Poke RNG',version:'test',platform:'win32'}));
  const main=new BrowserWindow({width:1440,height:920,show:false,webPreferences:{preload:path.join(root,'electron/preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true,backgroundThrottling:false}});
  const loadWindow=(window,query={})=>window.loadFile(path.join(root,'dist/index.html'),{query});
  registerPanelWindows({getMainWindow:()=>main,loadWindow});
  const scriptRoot=fs.mkdtempSync(path.join(output,'scripts-'));
  fs.mkdirSync(path.join(scriptRoot,'测试'));
  fs.writeFileSync(path.join(scriptRoot,'测试','验证.rng'),'A 50\nWAIT 50\nB 50');
  registerScriptFiles({getMainWindow:()=>main,rootDirectory:scriptRoot});
  devices=registerDevices({ipcMain,getWindows:()=>BrowserWindow.getAllWindows(),rootDirectory:scriptRoot,testMode:true});
  await loadWindow(main);
  main.showInactive();
  await until(()=>js(main,'Boolean(window.desktop)'), 'desktop ready');
  await js(main,"document.querySelector('[aria-label=\"视频源：未尝试连接\"]').click()");
  await until(()=>js(main,"Array.from(document.querySelectorAll('option')).some(x=>x.value==='synthetic')"),'devices enumerated');
  await js(main,`(()=>{const select=document.querySelector('[aria-label="视频设备"]');select.value='synthetic';select.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  await js(main,`Array.from(document.querySelectorAll('button')).find(x=>x.textContent==='连接视频源').click()`);
  await until(()=>js(main,"Boolean(document.querySelector('[aria-label=\"视频源：连接成功\"]'))"),'real connection state');
  await js(main,"document.querySelector('[aria-label=\"关闭视频源\"]').click();document.querySelector('[aria-label=\"视频预览\"]').click()");
  await until(()=>js(main,"document.querySelector('.preview-frame img')?.naturalWidth>0"),'inline live frames decoded');
  await js(main,"document.querySelector('[aria-label=\"标签\"]').click()");
  await until(()=>js(main,"document.querySelector('.label-monitor-frame img')?.naturalWidth>0"),'labels live consumer');
  await js(main,"Array.from(document.querySelectorAll('button')).find(x=>x.textContent==='截图').click()");
  await until(()=>js(main,"document.querySelector('.snapshot-video')?.naturalWidth===1920"),'snapshot retains source resolution');
  assert.equal(await js(main,`(()=>{
    const image=document.querySelector('.snapshot-video').getBoundingClientRect();
    const stage=document.querySelector('.label-snapshot-stage').getBoundingClientRect();
    return image.left>=stage.left && image.top>=stage.top && image.right<=stage.right && image.bottom<=stage.bottom;
  })()`),true,'full-resolution snapshot fits the existing canvas');
  await delay(200);
  fs.writeFileSync(path.join(output,'video-inline.png'),(await main.webContents.capturePage()).toPNG());
  const original=await js(main,'window.desktop.devices.getState().then(x=>x.video.session)');
  await js(main,"document.querySelector('[aria-label=\"弹出为独立窗口\"]').click()");
  await until(()=>BrowserWindow.getAllWindows().length===2,'detached video');
  const detached=BrowserWindow.getAllWindows().find(x=>x!==main);
  await until(()=>js(detached,"document.querySelector('.label-monitor-frame img')?.naturalWidth>0"),'detached live consumer');
  await until(()=>js(detached,"document.querySelector('.snapshot-video')?.naturalWidth===1920"),'snapshot survives detach');
  assert.equal(await js(main,'window.desktop.devices.getState().then(x=>x.video.session)'),original);
  detached.close();
  assert.equal(await js(main,'window.desktop.devices.getState().then(x=>x.video.status)'),'connected');
  await js(main,"document.querySelector('[aria-label=\"伊机控：未尝试连接\"]').click()");
  await until(()=>js(main,"Array.from(document.querySelectorAll('option')).some(x=>x.value==='mock')"),'serial ports enumerated');
  await js(main,`(()=>{const select=document.querySelector('[aria-label="伊机控串口"]');select.value='mock';select.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  await js(main,"Array.from(document.querySelectorAll('button')).find(x=>x.textContent==='连接伊机控').click()");
  await until(()=>js(main,"Boolean(document.querySelector('[aria-label=\"伊机控：连接成功\"]'))"),'controller connected');
  await js(main,"document.querySelector('[aria-label=\"关闭伊机控连接\"]').click()");
  await js(main,"Array.from(document.querySelectorAll('button')).find(x=>x.textContent.includes('虚拟手柄')).click()");
  await until(()=>BrowserWindow.getAllWindows().length===2,'virtual controller overlay window');
  const overlay=BrowserWindow.getAllWindows().find(x=>x!==main);
  await until(()=>js(overlay,"Boolean(document.querySelector('[aria-label=\"虚拟手柄状态浮窗\"]'))"),'virtual controller overlay');
  await until(()=>js(main,'window.desktop.overlay.getState().then(x=>x.active)'),'virtual controller active');
  await js(overlay,"window.desktop.overlay.toggleActive()");
  await until(()=>js(main,'window.desktop.overlay.getState().then(x=>x.mode)'), 'virtual controller standby');
  await delay(160);
  await js(overlay,"window.desktop.overlay.toggleActive()");
  await until(()=>js(main,'window.desktop.overlay.getState().then(x=>x.active)'),'virtual controller restored active');
  await js(main,"Array.from(document.querySelectorAll('button')).find(x=>x.textContent.includes('按键映射')).click()");
  await until(()=>js(main,"Boolean(document.querySelector('[aria-label=\"按键设置\"]'))"),'key mapping dialog');
  await until(()=>js(main,'window.desktop.overlay.getState().then(x=>!x.active)'),'mapping suspends virtual controller');
  await js(main,"document.querySelector('[aria-label^=\"A：\"]').click()");
  await delay(50);
  await js(main,"window.dispatchEvent(new KeyboardEvent('keydown',{key:'p',code:'KeyP',bubbles:true}))");
  await delay(50);
  fs.writeFileSync(path.join(output,'mapping.png'),(await main.webContents.capturePage()).toPNG());
  assert.equal(await js(main,"document.querySelector('[aria-label^=\"A：\"]').getAttribute('aria-label')"),'A：P');
  await js(main,"document.querySelector('.mapping-reset').click();document.querySelector('.key-mapping-actions .primary').click()");
  await until(()=>js(main,"!document.querySelector('[aria-label=\"按键设置\"]')"),'key mapping saved');
  await until(()=>js(main,'window.desktop.overlay.getState().then(x=>x.active)'),'mapping restores virtual controller');
  await js(main,"window.desktop.overlay.hide()");
  if (!await js(main,"Boolean(document.querySelector('[aria-label=\"选择脚本：验证\"]'))")) await js(main,"document.querySelector('[aria-label=\"文件夹：测试\"]').click()");
  await until(()=>js(main,"Boolean(document.querySelector('[aria-label=\"选择脚本：验证\"]'))"),'script folder opened');
  await js(main,"document.querySelector('[aria-label=\"选择脚本：验证\"]').click()");
  await until(()=>js(main,"document.querySelector('textarea')?.value.includes('A 50')"),'script selected');
  await js(main,"Array.from(document.querySelectorAll('button')).find(x=>x.textContent==='开始运行').click()");
  await until(()=>js(main,"document.querySelector('.log-stream')?.textContent.includes('脚本执行完成')"),'native execution finished');
  assert.equal(await js(main,'window.desktop.devices.getState().then(x=>x.controller.status)'),'connected');
  await js(main,'window.desktop.devices.video.disconnect()');
  await devices.close();
  clearTimeout(timeout); console.log('PASS: source picker, capture, preview, full-resolution snapshot, detach, serial picker, buttons, script engine and cleanup.'); app.exit(0);
}).catch(async error=>{console.error(error);if(devices)await devices.close();app.exit(1);});
