const { app, BrowserWindow, ipcMain } = require('electron');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { registerDevices } = require('../electron/devices.cjs');
const { registerPanelWindows } = require('../electron/panel-windows.cjs');
const { registerScriptFiles } = require('../electron/script-files.cjs');

const root = path.resolve(__dirname, '..');
const output = path.join(root, 'node_modules/.tmp/script-editor-review');
fs.mkdirSync(output, { recursive: true });
app.setPath('userData', path.join(output, 'profile'));
app.commandLine.appendSwitch('disable-gpu');
let devices;
const timeout = setTimeout(() => { console.error('Script editor timeout'); app.exit(1); }, 45000);
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
async function until(read, label) {
  for (let i = 0; i < 160; i++) { if (await read()) return; await delay(35); }
  throw new Error('Timed out: ' + label);
}
app.whenReady().then(async () => {
  ipcMain.handle('app:metadata', () => ({ name: 'test', version: 'test', platform: 'win32' }));
  const main = new BrowserWindow({ width: 1440, height: 920, show: false, webPreferences: {
    preload: path.join(root, 'electron/preload.cjs'), contextIsolation: true, nodeIntegration: false, sandbox: true, backgroundThrottling: false,
  } });
  const errors = [];
  main.webContents.on('console-message', event => { if (event.level === 'error') errors.push(event.message); });
  const loadWindow = (window, query = {}) => window.loadFile(path.join(root, 'dist/index.html'), { query });
  const scriptRoot = fs.mkdtempSync(path.join(output, 'scripts-'));
  fs.writeFileSync(path.join(scriptRoot, '追踪.rng'), '# edit me\nA 50');
  fs.writeFileSync(path.join(scriptRoot, '另一个.rng'), 'WAIT 50');
  fs.mkdirSync(path.join(scriptRoot, 'lib'));
  fs.writeFileSync(path.join(scriptRoot, 'lib/动作.ecs'), 'FUNC hold\nWAIT 3000\nENDFUNC');
  registerScriptFiles({ getMainWindow: () => main, rootDirectory: scriptRoot });
  registerPanelWindows({ getMainWindow: () => main, loadWindow });
  devices = registerDevices({ ipcMain, getWindows: () => BrowserWindow.getAllWindows(), rootDirectory: scriptRoot, testMode: true });
  const js = code => main.webContents.executeJavaScript(code, true).catch(error => { throw new Error(code + '\n' + error.message + '\n' + errors.join('\n')); });
  const button = text => js(`[...document.querySelectorAll('button')].find(x => x.textContent === ${JSON.stringify(text)}).click()`);
  const select = name => js(`document.querySelector(${JSON.stringify('[aria-label="选择脚本：' + name + '"]')}).click()`);
  const edit = text => js(`(() => { const e = document.querySelector('[aria-label="脚本内容"]'); Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, 'value').set.call(e, ${JSON.stringify(text)}); e.dispatchEvent(new Event('input', { bubbles: true })); })()`);
  const screenshot = async name => fs.writeFileSync(path.join(output, name + '.png'), (await main.webContents.capturePage()).toPNG());
  await loadWindow(main);
  main.showInactive();
  await until(() => js('Boolean(document.querySelector("textarea"))'), 'editor');
  await select('追踪');
  await until(() => js('Boolean(document.querySelector(".syntax-status.valid"))'), 'offline validation');
  await edit('# 语法错误示例\nLS UP 200');
  await until(() => js('Boolean(document.querySelector(".syntax-status.invalid"))'), 'syntax error');
  assert.equal(await js('document.querySelector(".line-numbers .has-syntax-error").dataset.line'), '2');
  assert.match(await js('document.querySelector(".syntax-status").textContent'), /无效摇杆方向/);
  await button('定位错误');
  assert.equal(await js('document.querySelector("textarea").selectionStart'), '# 语法错误示例\n'.length);
  await screenshot('syntax-error');

  const longScript = [...Array.from({ length: 35 }, (_, i) => `# 准备步骤 ${i + 1}`), 'FOR 3', '  WAIT 1200', '  A 50', 'NEXT'].join('\n');
  await edit(longScript);
  await until(() => js('Boolean(document.querySelector(".syntax-status.valid"))'), 'error cleared');
  assert.equal(await js('document.querySelectorAll(".has-syntax-error").length'), 0);
  await js('window.desktop.devices.controller.connect("mock")');
  await button('开始运行');
  await until(() => js('document.querySelector(".line-numbers .is-running")?.dataset.line === "37"'), 'running line');
  assert.ok(await js('document.querySelector("textarea").scrollTop > 0'), 'execution line follows scroll');
  assert.match(await js('document.querySelector(".execution-preview").textContent'), /循环 · 1 \/ 3/);
  await screenshot('execution-follow');
  await edit('# 运行后修改的草稿\nA 50');
  assert.equal(await js('document.querySelectorAll(".is-running").length'), 0, 'no incorrect mark over edited text');
  assert.equal(await js('document.querySelector(".execution-source-line").textContent'), '  WAIT 1200', 'frozen execution text');
  await select('另一个');
  assert.equal(await js('document.querySelectorAll(".is-running").length'), 0, 'other script has no marker');
  assert.match(await js('document.querySelector(".execution-preview").textContent'), /追踪.rng/);
  await button('停止运行');
  await until(() => js('!document.querySelector(".execution-preview")'), 'stop clears location');
  await select('追踪');
  assert.match(await js('document.querySelector("textarea").value'), /运行后修改的草稿/, 'unsaved edit retained');
  await edit('IMPORT "动作.ecs"\nCALL hold');
  await until(() => js('Boolean(document.querySelector(".syntax-status.valid"))'), 'library syntax valid');
  await button('开始运行');
  await until(() => js('document.querySelector(".execution-preview")?.textContent.includes("lib/动作.ecs · 第 2 行")'), 'library execution location');
  assert.equal(await js('document.querySelectorAll(".is-running").length'), 0, 'library line never marks main source');
  await screenshot('library-execution');
  await button('停止运行');
  await until(() => js('!document.querySelector(".execution-preview")'), 'library stop');
  await edit('FOR 80\n  WAIT 50\nNEXT');
  await until(() => js('Boolean(document.querySelector(".syntax-status.valid"))'), 'fast progress script valid');
  await button('开始运行');
  await until(() => js('document.querySelector(".execution-preview")?.textContent.includes("循环")'), 'fast progress started');
  await until(() => js('document.querySelector("[aria-label=\\"执行时长\\"]").textContent === "00:00:01"'), 'timer advances during frequent progress');
  assert.ok(await js('Boolean(document.querySelector(".execution-preview"))'), 'timer advances before execution finishes');
  await button('停止运行');
  await until(() => js('!document.querySelector(".execution-preview")'), 'fast progress stop');
  await edit('WAIT 100');
  await until(() => js('Boolean(document.querySelector(".syntax-status.valid"))'), 'valid short script');
  await button('开始运行');
  await until(() => js('document.querySelector(".log-stream")?.textContent.includes("脚本执行完成")'), 'completion');
  assert.equal(await js('document.querySelectorAll(".is-running, .execution-preview").length'), 0);

  fs.writeFileSync(path.join(scriptRoot, 'lib/动作.ecs'), 'FUNC hold\nBAD_COMMAND\nENDFUNC');
  await edit('CALL hold');
  await until(() => js('Boolean(document.querySelector(".syntax-status.invalid"))'), 'library diagnostic');
  assert.match(await js('document.querySelector(".syntax-status").textContent'), /lib\/动作.ecs:2/);
  assert.equal(await js('document.querySelectorAll(".has-syntax-error").length'), 0, 'library error does not paint main line');
  await button('帮助');
  await until(() => js('Boolean(document.querySelector(".script-help-dialog"))'), 'help opened');
  await delay(180);
  await screenshot('help');
  assert.equal(await js('document.querySelector(".script-help-dialog").scrollWidth <= document.querySelector(".script-help-dialog").clientWidth'), true);
  assert.equal(await js('document.querySelectorAll(".help-section").length'), 6);
  await js('document.querySelector(".script-help-dialog .dialog-body").scrollTop = 100000');
  await delay(120);
  await screenshot('help-functions');
  await js('document.querySelector("[aria-label=\\"关闭脚本编辑帮助\\"]").click()');
  main.setSize(1100, 680);
  await delay(180);
  await screenshot('compact-error');
  assert.ok(await js('document.querySelector("textarea").getBoundingClientRect().height > 80'), 'compact editor remains usable');
  fs.writeFileSync(path.join(scriptRoot, 'lib/动作.ecs'), 'FUNC hold\nWAIT 3000\nENDFUNC');
  await edit(longScript);
  await until(() => js('Boolean(document.querySelector(".syntax-status.valid"))'), 'compact script valid');
  await button('开始运行');
  await until(() => js('document.querySelector(".line-numbers .is-running")?.dataset.line === "37"'), 'compact execution');
  assert.ok(await js('document.querySelector("textarea").getBoundingClientRect().height > 80'), 'compact execution leaves editor room');
  const alignment = await js('(() => { const n=document.querySelector(".line-numbers .is-running").getBoundingClientRect(); const h=document.querySelector(".editor-line-mark.is-running").getBoundingClientRect(); return Math.abs(n.top-h.top); })()');
  assert.ok(alignment < 1, 'gutter and execution highlight stay aligned after scrolling');
  await screenshot('compact-execution');
  await button('停止运行');
  await until(() => js('!document.querySelector(".execution-preview")'), 'compact stop');
  assert.deepEqual(errors, []);
  await devices.close();
  clearTimeout(timeout);
  console.log('PASS: offline compiler diagnostics, location, correction, execution scroll/loops/timer, immutable source, library progress/errors, stop/completion, help, screenshots.');
  app.exit(0);
}).catch(async error => { console.error(error); await devices?.close(); app.exit(1); });
