// Generated from the bundled FRLG personal data and original GUI translations.
export const FRLG_SPECIES_METADATA = {
  "Bulbasaur": {"id": 1, "label": "妙蛙种子", "abilities": ["Overgrow"]},
  "Ivysaur": {"id": 2, "label": "妙蛙草", "abilities": ["Overgrow"]},
  "Venusaur": {"id": 3, "label": "妙蛙花", "abilities": ["Overgrow"]},
  "Charmander": {"id": 4, "label": "小火龙", "abilities": ["Blaze"]},
  "Charmeleon": {"id": 5, "label": "火恐龙", "abilities": ["Blaze"]},
  "Charizard": {"id": 6, "label": "喷火龙", "abilities": ["Blaze"]},
  "Squirtle": {"id": 7, "label": "杰尼龟", "abilities": ["Torrent"]},
  "Wartortle": {"id": 8, "label": "卡咪龟", "abilities": ["Torrent"]},
  "Blastoise": {"id": 9, "label": "水箭龟", "abilities": ["Torrent"]},
  "Caterpie": {"id": 10, "label": "绿毛虫", "abilities": ["Shield Dust"]},
  "Metapod": {"id": 11, "label": "铁甲蛹", "abilities": ["Shed Skin"]},
  "Butterfree": {"id": 12, "label": "巴大蝶", "abilities": ["Compound Eyes"]},
  "Weedle": {"id": 13, "label": "独角虫", "abilities": ["Shield Dust"]},
  "Kakuna": {"id": 14, "label": "铁壳蛹", "abilities": ["Shed Skin"]},
  "Beedrill": {"id": 15, "label": "大针蜂", "abilities": ["Swarm"]},
  "Pidgey": {"id": 16, "label": "波波", "abilities": ["Keen Eye"]},
  "Pidgeotto": {"id": 17, "label": "比比鸟", "abilities": ["Keen Eye"]},
  "Pidgeot": {"id": 18, "label": "大比鸟", "abilities": ["Keen Eye"]},
  "Rattata": {"id": 19, "label": "小拉达", "abilities": ["Run Away", "Guts"]},
  "Raticate": {"id": 20, "label": "拉达", "abilities": ["Run Away", "Guts"]},
  "Spearow": {"id": 21, "label": "烈雀", "abilities": ["Keen Eye"]},
  "Fearow": {"id": 22, "label": "大嘴雀", "abilities": ["Keen Eye"]},
  "Ekans": {"id": 23, "label": "阿柏蛇", "abilities": ["Intimidate", "Shed Skin"]},
  "Arbok": {"id": 24, "label": "阿柏怪", "abilities": ["Intimidate", "Shed Skin"]},
  "Pikachu": {"id": 25, "label": "皮卡丘", "abilities": ["Static"]},
  "Raichu": {"id": 26, "label": "雷丘", "abilities": ["Static"]},
  "Sandshrew": {"id": 27, "label": "穿山鼠", "abilities": ["Sand Veil"]},
  "Sandslash": {"id": 28, "label": "穿山王", "abilities": ["Sand Veil"]},
  "Nidoran♀": {"id": 29, "label": "尼多兰", "abilities": ["Poison Point"]},
  "Nidorina": {"id": 30, "label": "尼多娜", "abilities": ["Poison Point"]},
  "Nidoqueen": {"id": 31, "label": "尼多后", "abilities": ["Poison Point"]},
  "Nidoran♂": {"id": 32, "label": "尼多朗", "abilities": ["Poison Point"]},
  "Nidorino": {"id": 33, "label": "尼多力诺", "abilities": ["Poison Point"]},
  "Nidoking": {"id": 34, "label": "尼多王", "abilities": ["Poison Point"]},
  "Clefairy": {"id": 35, "label": "皮皮", "abilities": ["Cute Charm"]},
  "Clefable": {"id": 36, "label": "皮可西", "abilities": ["Cute Charm"]},
  "Vulpix": {"id": 37, "label": "六尾", "abilities": ["Flash Fire"]},
  "Ninetales": {"id": 38, "label": "九尾", "abilities": ["Flash Fire"]},
  "Jigglypuff": {"id": 39, "label": "胖丁", "abilities": ["Cute Charm"]},
  "Wigglytuff": {"id": 40, "label": "胖可丁", "abilities": ["Cute Charm"]},
  "Zubat": {"id": 41, "label": "超音蝠", "abilities": ["Inner Focus"]},
  "Golbat": {"id": 42, "label": "大嘴蝠", "abilities": ["Inner Focus"]},
  "Oddish": {"id": 43, "label": "走路草", "abilities": ["Chlorophyll"]},
  "Gloom": {"id": 44, "label": "臭臭花", "abilities": ["Chlorophyll"]},
  "Vileplume": {"id": 45, "label": "霸王花", "abilities": ["Chlorophyll"]},
  "Paras": {"id": 46, "label": "派拉斯", "abilities": ["Effect Spore"]},
  "Parasect": {"id": 47, "label": "派拉斯特", "abilities": ["Effect Spore"]},
  "Venonat": {"id": 48, "label": "毛球", "abilities": ["Compound Eyes"]},
  "Venomoth": {"id": 49, "label": "摩鲁蛾", "abilities": ["Shield Dust"]},
  "Diglett": {"id": 50, "label": "地鼠", "abilities": ["Sand Veil", "Arena Trap"]},
  "Dugtrio": {"id": 51, "label": "三地鼠", "abilities": ["Sand Veil", "Arena Trap"]},
  "Meowth": {"id": 52, "label": "喵喵", "abilities": ["Pickup"]},
  "Persian": {"id": 53, "label": "猫老大", "abilities": ["Limber"]},
  "Psyduck": {"id": 54, "label": "可达鸭", "abilities": ["Damp", "Cloud Nine"]},
  "Golduck": {"id": 55, "label": "哥达鸭", "abilities": ["Damp", "Cloud Nine"]},
  "Mankey": {"id": 56, "label": "猴怪", "abilities": ["Vital Spirit"]},
  "Primeape": {"id": 57, "label": "火爆猴", "abilities": ["Vital Spirit"]},
  "Growlithe": {"id": 58, "label": "卡蒂狗", "abilities": ["Intimidate", "Flash Fire"]},
  "Arcanine": {"id": 59, "label": "风速狗", "abilities": ["Intimidate", "Flash Fire"]},
  "Poliwag": {"id": 60, "label": "蚊香蝌蚪", "abilities": ["Water Absorb", "Damp"]},
  "Poliwhirl": {"id": 61, "label": "蚊香君", "abilities": ["Water Absorb", "Damp"]},
  "Poliwrath": {"id": 62, "label": "蚊香泳士", "abilities": ["Water Absorb", "Damp"]},
  "Abra": {"id": 63, "label": "凯西", "abilities": ["Synchronize", "Inner Focus"]},
  "Kadabra": {"id": 64, "label": "勇基拉", "abilities": ["Synchronize", "Inner Focus"]},
  "Alakazam": {"id": 65, "label": "胡地", "abilities": ["Synchronize", "Inner Focus"]},
  "Machop": {"id": 66, "label": "腕力", "abilities": ["Guts"]},
  "Machoke": {"id": 67, "label": "豪力", "abilities": ["Guts"]},
  "Machamp": {"id": 68, "label": "怪力", "abilities": ["Guts"]},
  "Bellsprout": {"id": 69, "label": "喇叭芽", "abilities": ["Chlorophyll"]},
  "Weepinbell": {"id": 70, "label": "口呆花", "abilities": ["Chlorophyll"]},
  "Victreebel": {"id": 71, "label": "大食花", "abilities": ["Chlorophyll"]},
  "Tentacool": {"id": 72, "label": "玛瑙水母", "abilities": ["Clear Body", "Liquid Ooze"]},
  "Tentacruel": {"id": 73, "label": "毒刺水母", "abilities": ["Clear Body", "Liquid Ooze"]},
  "Geodude": {"id": 74, "label": "小拳石", "abilities": ["Rock Head", "Sturdy"]},
  "Graveler": {"id": 75, "label": "隆隆石", "abilities": ["Rock Head", "Sturdy"]},
  "Golem": {"id": 76, "label": "隆隆岩", "abilities": ["Rock Head", "Sturdy"]},
  "Ponyta": {"id": 77, "label": "小火马", "abilities": ["Run Away", "Flash Fire"]},
  "Rapidash": {"id": 78, "label": "烈焰马", "abilities": ["Run Away", "Flash Fire"]},
  "Slowpoke": {"id": 79, "label": "呆呆兽", "abilities": ["Oblivious", "Own Tempo"]},
  "Slowbro": {"id": 80, "label": "呆壳兽", "abilities": ["Oblivious", "Own Tempo"]},
  "Magnemite": {"id": 81, "label": "小磁怪", "abilities": ["Magnet Pull", "Sturdy"]},
  "Magneton": {"id": 82, "label": "三合一磁怪", "abilities": ["Magnet Pull", "Sturdy"]},
  "Farfetch’d": {"id": 83, "label": "Farfetch’d", "abilities": ["Keen Eye", "Inner Focus"]},
  "Doduo": {"id": 84, "label": "嘟嘟", "abilities": ["Run Away", "Early Bird"]},
  "Dodrio": {"id": 85, "label": "嘟嘟利", "abilities": ["Run Away", "Early Bird"]},
  "Seel": {"id": 86, "label": "小海狮", "abilities": ["Thick Fat"]},
  "Dewgong": {"id": 87, "label": "白海狮", "abilities": ["Thick Fat"]},
  "Grimer": {"id": 88, "label": "臭泥", "abilities": ["Stench", "Sticky Hold"]},
  "Muk": {"id": 89, "label": "臭臭泥", "abilities": ["Stench", "Sticky Hold"]},
  "Shellder": {"id": 90, "label": "大舌贝", "abilities": ["Shell Armor"]},
  "Cloyster": {"id": 91, "label": "刺甲贝", "abilities": ["Shell Armor"]},
  "Gastly": {"id": 92, "label": "鬼斯", "abilities": ["Levitate"]},
  "Haunter": {"id": 93, "label": "鬼斯通", "abilities": ["Levitate"]},
  "Gengar": {"id": 94, "label": "耿鬼", "abilities": ["Levitate"]},
  "Onix": {"id": 95, "label": "大岩蛇", "abilities": ["Rock Head", "Sturdy"]},
  "Drowzee": {"id": 96, "label": "催眠貘", "abilities": ["Insomnia"]},
  "Hypno": {"id": 97, "label": "引梦貘人", "abilities": ["Insomnia"]},
  "Krabby": {"id": 98, "label": "大钳蟹", "abilities": ["Hyper Cutter", "Shell Armor"]},
  "Kingler": {"id": 99, "label": "巨钳蟹", "abilities": ["Hyper Cutter", "Shell Armor"]},
  "Voltorb": {"id": 100, "label": "霹雳电球", "abilities": ["Soundproof", "Static"]},
  "Electrode": {"id": 101, "label": "顽皮雷弹", "abilities": ["Soundproof", "Static"]},
  "Exeggcute": {"id": 102, "label": "蛋蛋", "abilities": ["Chlorophyll"]},
  "Exeggutor": {"id": 103, "label": "椰蛋树", "abilities": ["Chlorophyll"]},
  "Cubone": {"id": 104, "label": "卡拉卡拉", "abilities": ["Rock Head", "Lightning Rod"]},
  "Marowak": {"id": 105, "label": "嘎啦嘎啦", "abilities": ["Rock Head", "Lightning Rod"]},
  "Hitmonlee": {"id": 106, "label": "飞腿郎", "abilities": ["Limber"]},
  "Hitmonchan": {"id": 107, "label": "快拳郎", "abilities": ["Keen Eye"]},
  "Lickitung": {"id": 108, "label": "大舌头", "abilities": ["Own Tempo", "Oblivious"]},
  "Koffing": {"id": 109, "label": "瓦斯弹", "abilities": ["Levitate"]},
  "Weezing": {"id": 110, "label": "双弹瓦斯", "abilities": ["Levitate"]},
  "Rhyhorn": {"id": 111, "label": "独角犀牛", "abilities": ["Lightning Rod", "Rock Head"]},
  "Rhydon": {"id": 112, "label": "钻角犀兽", "abilities": ["Lightning Rod", "Rock Head"]},
  "Chansey": {"id": 113, "label": "吉利蛋", "abilities": ["Natural Cure", "Serene Grace"]},
  "Tangela": {"id": 114, "label": "蔓藤怪", "abilities": ["Chlorophyll"]},
  "Kangaskhan": {"id": 115, "label": "袋兽", "abilities": ["Early Bird"]},
  "Horsea": {"id": 116, "label": "墨海马", "abilities": ["Swift Swim"]},
  "Seadra": {"id": 117, "label": "海刺龙", "abilities": ["Poison Point"]},
  "Goldeen": {"id": 118, "label": "角金鱼", "abilities": ["Swift Swim", "Water Veil"]},
  "Seaking": {"id": 119, "label": "金鱼王", "abilities": ["Swift Swim", "Water Veil"]},
  "Staryu": {"id": 120, "label": "海星星", "abilities": ["Illuminate", "Natural Cure"]},
  "Starmie": {"id": 121, "label": "宝石海星", "abilities": ["Illuminate", "Natural Cure"]},
  "Mr. Mime": {"id": 122, "label": "魔墙人偶", "abilities": ["Soundproof"]},
  "Scyther": {"id": 123, "label": "飞天螳螂", "abilities": ["Swarm"]},
  "Jynx": {"id": 124, "label": "迷唇姐", "abilities": ["Oblivious"]},
  "Electabuzz": {"id": 125, "label": "电击兽", "abilities": ["Static"]},
  "Magmar": {"id": 126, "label": "鸭嘴火兽", "abilities": ["Flame Body"]},
  "Pinsir": {"id": 127, "label": "凯罗斯", "abilities": ["Hyper Cutter"]},
  "Tauros": {"id": 128, "label": "肯泰罗", "abilities": ["Intimidate"]},
  "Magikarp": {"id": 129, "label": "鲤鱼王", "abilities": ["Swift Swim"]},
  "Gyarados": {"id": 130, "label": "暴鲤龙", "abilities": ["Intimidate"]},
  "Lapras": {"id": 131, "label": "拉普拉斯", "abilities": ["Water Absorb", "Shell Armor"]},
  "Ditto": {"id": 132, "label": "百变怪", "abilities": ["Limber"]},
  "Eevee": {"id": 133, "label": "伊布", "abilities": ["Run Away"]},
  "Vaporeon": {"id": 134, "label": "水伊布", "abilities": ["Water Absorb"]},
  "Jolteon": {"id": 135, "label": "雷伊布", "abilities": ["Volt Absorb"]},
  "Flareon": {"id": 136, "label": "火伊布", "abilities": ["Flash Fire"]},
  "Porygon": {"id": 137, "label": "多边兽", "abilities": ["Trace"]},
  "Omanyte": {"id": 138, "label": "菊石兽", "abilities": ["Swift Swim", "Shell Armor"]},
  "Omastar": {"id": 139, "label": "多刺菊石兽", "abilities": ["Swift Swim", "Shell Armor"]},
  "Kabuto": {"id": 140, "label": "化石盔", "abilities": ["Swift Swim", "Battle Armor"]},
  "Kabutops": {"id": 141, "label": "镰刀盔", "abilities": ["Swift Swim", "Battle Armor"]},
  "Aerodactyl": {"id": 142, "label": "化石翼龙", "abilities": ["Rock Head", "Pressure"]},
  "Snorlax": {"id": 143, "label": "卡比兽", "abilities": ["Immunity", "Thick Fat"]},
  "Articuno": {"id": 144, "label": "急冻鸟", "abilities": ["Pressure"]},
  "Zapdos": {"id": 145, "label": "闪电鸟", "abilities": ["Pressure"]},
  "Moltres": {"id": 146, "label": "火焰鸟", "abilities": ["Pressure"]},
  "Dratini": {"id": 147, "label": "迷你龙", "abilities": ["Shed Skin"]},
  "Dragonair": {"id": 148, "label": "哈克龙", "abilities": ["Shed Skin"]},
  "Dragonite": {"id": 149, "label": "快龙", "abilities": ["Inner Focus"]},
  "Mewtwo": {"id": 150, "label": "超梦", "abilities": ["Pressure"]},
  "Mew": {"id": 151, "label": "梦幻", "abilities": ["Synchronize"]},
  "Chikorita": {"id": 152, "label": "菊草叶", "abilities": ["Overgrow"]},
  "Bayleef": {"id": 153, "label": "月桂叶", "abilities": ["Overgrow"]},
  "Meganium": {"id": 154, "label": "大竺葵", "abilities": ["Overgrow"]},
  "Cyndaquil": {"id": 155, "label": "火球鼠", "abilities": ["Blaze"]},
  "Quilava": {"id": 156, "label": "火岩鼠", "abilities": ["Blaze"]},
  "Typhlosion": {"id": 157, "label": "火暴兽", "abilities": ["Blaze"]},
  "Totodile": {"id": 158, "label": "小锯鳄", "abilities": ["Torrent"]},
  "Croconaw": {"id": 159, "label": "蓝鳄", "abilities": ["Torrent"]},
  "Feraligatr": {"id": 160, "label": "大力鳄", "abilities": ["Torrent"]},
  "Sentret": {"id": 161, "label": "尾立", "abilities": ["Run Away", "Keen Eye"]},
  "Furret": {"id": 162, "label": "大尾立", "abilities": ["Run Away", "Keen Eye"]},
  "Hoothoot": {"id": 163, "label": "咕咕", "abilities": ["Insomnia", "Keen Eye"]},
  "Noctowl": {"id": 164, "label": "猫头夜鹰", "abilities": ["Insomnia", "Keen Eye"]},
  "Ledyba": {"id": 165, "label": "芭瓢虫", "abilities": ["Swarm", "Early Bird"]},
  "Ledian": {"id": 166, "label": "安瓢虫", "abilities": ["Swarm", "Early Bird"]},
  "Spinarak": {"id": 167, "label": "圆丝蛛", "abilities": ["Swarm", "Insomnia"]},
  "Ariados": {"id": 168, "label": "阿利多斯", "abilities": ["Swarm", "Insomnia"]},
  "Crobat": {"id": 169, "label": "叉字蝠", "abilities": ["Inner Focus"]},
  "Chinchou": {"id": 170, "label": "灯笼鱼", "abilities": ["Volt Absorb", "Illuminate"]},
  "Lanturn": {"id": 171, "label": "电灯怪", "abilities": ["Volt Absorb", "Illuminate"]},
  "Pichu": {"id": 172, "label": "皮丘", "abilities": ["Static"]},
  "Cleffa": {"id": 173, "label": "皮宝宝", "abilities": ["Cute Charm"]},
  "Igglybuff": {"id": 174, "label": "宝宝丁", "abilities": ["Cute Charm"]},
  "Togepi": {"id": 175, "label": "波克比", "abilities": ["Hustle", "Serene Grace"]},
  "Togetic": {"id": 176, "label": "波克基古", "abilities": ["Hustle", "Serene Grace"]},
  "Natu": {"id": 177, "label": "天然雀", "abilities": ["Synchronize", "Early Bird"]},
  "Xatu": {"id": 178, "label": "天然鸟", "abilities": ["Synchronize", "Early Bird"]},
  "Mareep": {"id": 179, "label": "咩利羊", "abilities": ["Static"]},
  "Flaaffy": {"id": 180, "label": "茸茸羊", "abilities": ["Static"]},
  "Ampharos": {"id": 181, "label": "电龙", "abilities": ["Static"]},
  "Bellossom": {"id": 182, "label": "美丽花", "abilities": ["Chlorophyll"]},
  "Marill": {"id": 183, "label": "玛力露", "abilities": ["Thick Fat", "Huge Power"]},
  "Azumarill": {"id": 184, "label": "玛力露丽", "abilities": ["Thick Fat", "Huge Power"]},
  "Sudowoodo": {"id": 185, "label": "树才怪", "abilities": ["Sturdy", "Rock Head"]},
  "Politoed": {"id": 186, "label": "蚊香蛙皇", "abilities": ["Water Absorb", "Damp"]},
  "Hoppip": {"id": 187, "label": "毽子草", "abilities": ["Chlorophyll"]},
  "Skiploom": {"id": 188, "label": "毽子花", "abilities": ["Chlorophyll"]},
  "Jumpluff": {"id": 189, "label": "毽子棉", "abilities": ["Chlorophyll"]},
  "Aipom": {"id": 190, "label": "长尾怪手", "abilities": ["Run Away", "Pickup"]},
  "Sunkern": {"id": 191, "label": "向日种子", "abilities": ["Chlorophyll"]},
  "Sunflora": {"id": 192, "label": "向日花怪", "abilities": ["Chlorophyll"]},
  "Yanma": {"id": 193, "label": "蜻蜻蜓", "abilities": ["Speed Boost", "Compound Eyes"]},
  "Wooper": {"id": 194, "label": "乌波", "abilities": ["Damp", "Water Absorb"]},
  "Quagsire": {"id": 195, "label": "沼王", "abilities": ["Damp", "Water Absorb"]},
  "Espeon": {"id": 196, "label": "太阳伊布", "abilities": ["Synchronize"]},
  "Umbreon": {"id": 197, "label": "月亮伊布", "abilities": ["Synchronize"]},
  "Murkrow": {"id": 198, "label": "黑暗鸦", "abilities": ["Insomnia"]},
  "Slowking": {"id": 199, "label": "呆呆王", "abilities": ["Oblivious", "Own Tempo"]},
  "Misdreavus": {"id": 200, "label": "梦妖", "abilities": ["Levitate"]},
  "Unown": {"id": 201, "label": "未知图腾", "abilities": ["Levitate"]},
  "Wobbuffet": {"id": 202, "label": "果然翁", "abilities": ["Shadow Tag"]},
  "Girafarig": {"id": 203, "label": "麒麟奇", "abilities": ["Inner Focus", "Early Bird"]},
  "Pineco": {"id": 204, "label": "榛果球", "abilities": ["Sturdy"]},
  "Forretress": {"id": 205, "label": "佛烈托斯", "abilities": ["Sturdy"]},
  "Dunsparce": {"id": 206, "label": "土龙弟弟", "abilities": ["Serene Grace", "Run Away"]},
  "Gligar": {"id": 207, "label": "天蝎", "abilities": ["Hyper Cutter", "Sand Veil"]},
  "Steelix": {"id": 208, "label": "大钢蛇", "abilities": ["Rock Head", "Sturdy"]},
  "Snubbull": {"id": 209, "label": "布鲁", "abilities": ["Intimidate", "Run Away"]},
  "Granbull": {"id": 210, "label": "布鲁皇", "abilities": ["Intimidate"]},
  "Qwilfish": {"id": 211, "label": "千针鱼", "abilities": ["Poison Point", "Swift Swim"]},
  "Scizor": {"id": 212, "label": "巨钳螳螂", "abilities": ["Swarm"]},
  "Shuckle": {"id": 213, "label": "壶壶", "abilities": ["Sturdy"]},
  "Heracross": {"id": 214, "label": "赫拉克罗斯", "abilities": ["Swarm", "Guts"]},
  "Sneasel": {"id": 215, "label": "狃拉", "abilities": ["Inner Focus", "Keen Eye"]},
  "Teddiursa": {"id": 216, "label": "熊宝宝", "abilities": ["Pickup"]},
  "Ursaring": {"id": 217, "label": "圈圈熊", "abilities": ["Guts"]},
  "Slugma": {"id": 218, "label": "熔岩虫", "abilities": ["Magma Armor", "Flame Body"]},
  "Magcargo": {"id": 219, "label": "熔岩蜗牛", "abilities": ["Magma Armor", "Flame Body"]},
  "Swinub": {"id": 220, "label": "小山猪", "abilities": ["Oblivious"]},
  "Piloswine": {"id": 221, "label": "长毛猪", "abilities": ["Oblivious"]},
  "Corsola": {"id": 222, "label": "太阳珊瑚", "abilities": ["Hustle", "Natural Cure"]},
  "Remoraid": {"id": 223, "label": "铁炮鱼", "abilities": ["Hustle"]},
  "Octillery": {"id": 224, "label": "章鱼桶", "abilities": ["Suction Cups"]},
  "Delibird": {"id": 225, "label": "信使鸟", "abilities": ["Vital Spirit", "Hustle"]},
  "Mantine": {"id": 226, "label": "巨翅飞鱼", "abilities": ["Swift Swim", "Water Absorb"]},
  "Skarmory": {"id": 227, "label": "盔甲鸟", "abilities": ["Keen Eye", "Sturdy"]},
  "Houndour": {"id": 228, "label": "戴鲁比", "abilities": ["Early Bird", "Flash Fire"]},
  "Houndoom": {"id": 229, "label": "黑鲁加", "abilities": ["Early Bird", "Flash Fire"]},
  "Kingdra": {"id": 230, "label": "刺龙王", "abilities": ["Swift Swim"]},
  "Phanpy": {"id": 231, "label": "小小象", "abilities": ["Pickup"]},
  "Donphan": {"id": 232, "label": "顿甲", "abilities": ["Sturdy"]},
  "Porygon2": {"id": 233, "label": "多边兽Ⅱ", "abilities": ["Trace"]},
  "Stantler": {"id": 234, "label": "惊角鹿", "abilities": ["Intimidate"]},
  "Smeargle": {"id": 235, "label": "图图犬", "abilities": ["Own Tempo"]},
  "Tyrogue": {"id": 236, "label": "无畏小子", "abilities": ["Guts"]},
  "Hitmontop": {"id": 237, "label": "战舞郎", "abilities": ["Intimidate"]},
  "Smoochum": {"id": 238, "label": "迷唇娃", "abilities": ["Oblivious"]},
  "Elekid": {"id": 239, "label": "电击怪", "abilities": ["Static"]},
  "Magby": {"id": 240, "label": "鸭嘴宝宝", "abilities": ["Flame Body"]},
  "Miltank": {"id": 241, "label": "大奶罐", "abilities": ["Thick Fat"]},
  "Blissey": {"id": 242, "label": "幸福蛋", "abilities": ["Natural Cure", "Serene Grace"]},
  "Raikou": {"id": 243, "label": "雷公", "abilities": ["Pressure"]},
  "Entei": {"id": 244, "label": "炎帝", "abilities": ["Pressure"]},
  "Suicune": {"id": 245, "label": "水君", "abilities": ["Pressure"]},
  "Larvitar": {"id": 246, "label": "幼基拉斯", "abilities": ["Guts"]},
  "Pupitar": {"id": 247, "label": "沙基拉斯", "abilities": ["Shed Skin"]},
  "Tyranitar": {"id": 248, "label": "班基拉斯", "abilities": ["Sand Stream"]},
  "Lugia": {"id": 249, "label": "洛奇亚", "abilities": ["Pressure"]},
  "Ho-Oh": {"id": 250, "label": "凤王", "abilities": ["Pressure"]},
  "Celebi": {"id": 251, "label": "时拉比", "abilities": ["Natural Cure"]},
  "Treecko": {"id": 252, "label": "木守宫", "abilities": ["Overgrow"]},
  "Grovyle": {"id": 253, "label": "森林蜥蜴", "abilities": ["Overgrow"]},
  "Sceptile": {"id": 254, "label": "蜥蜴王", "abilities": ["Overgrow"]},
  "Torchic": {"id": 255, "label": "火稚鸡", "abilities": ["Blaze"]},
  "Combusken": {"id": 256, "label": "力壮鸡", "abilities": ["Blaze"]},
  "Blaziken": {"id": 257, "label": "火焰鸡", "abilities": ["Blaze"]},
  "Mudkip": {"id": 258, "label": "水跃鱼", "abilities": ["Torrent"]},
  "Marshtomp": {"id": 259, "label": "沼跃鱼", "abilities": ["Torrent"]},
  "Swampert": {"id": 260, "label": "巨沼怪", "abilities": ["Torrent"]},
  "Poochyena": {"id": 261, "label": "土狼犬", "abilities": ["Run Away"]},
  "Mightyena": {"id": 262, "label": "大狼犬", "abilities": ["Intimidate"]},
  "Zigzagoon": {"id": 263, "label": "蛇纹熊", "abilities": ["Pickup"]},
  "Linoone": {"id": 264, "label": "直冲熊", "abilities": ["Pickup"]},
  "Wurmple": {"id": 265, "label": "刺尾虫", "abilities": ["Shield Dust"]},
  "Silcoon": {"id": 266, "label": "甲壳茧", "abilities": ["Shed Skin"]},
  "Beautifly": {"id": 267, "label": "狩猎凤蝶", "abilities": ["Swarm"]},
  "Cascoon": {"id": 268, "label": "盾甲茧", "abilities": ["Shed Skin"]},
  "Dustox": {"id": 269, "label": "毒粉蛾", "abilities": ["Shield Dust"]},
  "Lotad": {"id": 270, "label": "莲叶童子", "abilities": ["Swift Swim", "Rain Dish"]},
  "Lombre": {"id": 271, "label": "莲帽小童", "abilities": ["Swift Swim", "Rain Dish"]},
  "Ludicolo": {"id": 272, "label": "乐天河童", "abilities": ["Swift Swim", "Rain Dish"]},
  "Seedot": {"id": 273, "label": "橡实果", "abilities": ["Chlorophyll", "Early Bird"]},
  "Nuzleaf": {"id": 274, "label": "长鼻叶", "abilities": ["Chlorophyll", "Early Bird"]},
  "Shiftry": {"id": 275, "label": "狡猾天狗", "abilities": ["Chlorophyll", "Early Bird"]},
  "Taillow": {"id": 276, "label": "傲骨燕", "abilities": ["Guts"]},
  "Swellow": {"id": 277, "label": "大王燕", "abilities": ["Guts"]},
  "Wingull": {"id": 278, "label": "长翅鸥", "abilities": ["Keen Eye"]},
  "Pelipper": {"id": 279, "label": "大嘴鸥", "abilities": ["Keen Eye"]},
  "Ralts": {"id": 280, "label": "拉鲁拉丝", "abilities": ["Synchronize", "Trace"]},
  "Kirlia": {"id": 281, "label": "奇鲁莉安", "abilities": ["Synchronize", "Trace"]},
  "Gardevoir": {"id": 282, "label": "沙奈朵", "abilities": ["Synchronize", "Trace"]},
  "Surskit": {"id": 283, "label": "溜溜糖球", "abilities": ["Swift Swim"]},
  "Masquerain": {"id": 284, "label": "雨翅蛾", "abilities": ["Intimidate"]},
  "Shroomish": {"id": 285, "label": "蘑蘑菇", "abilities": ["Effect Spore"]},
  "Breloom": {"id": 286, "label": "斗笠菇", "abilities": ["Effect Spore"]},
  "Slakoth": {"id": 287, "label": "懒人獭", "abilities": ["Truant"]},
  "Vigoroth": {"id": 288, "label": "过动猿", "abilities": ["Vital Spirit"]},
  "Slaking": {"id": 289, "label": "请假王", "abilities": ["Truant"]},
  "Nincada": {"id": 290, "label": "土居忍士", "abilities": ["Compound Eyes"]},
  "Ninjask": {"id": 291, "label": "铁面忍者", "abilities": ["Speed Boost"]},
  "Shedinja": {"id": 292, "label": "脱壳忍者", "abilities": ["Wonder Guard"]},
  "Whismur": {"id": 293, "label": "咕妞妞", "abilities": ["Soundproof"]},
  "Loudred": {"id": 294, "label": "吼爆弹", "abilities": ["Soundproof"]},
  "Exploud": {"id": 295, "label": "爆音怪", "abilities": ["Soundproof"]},
  "Makuhita": {"id": 296, "label": "幕下力士", "abilities": ["Thick Fat", "Guts"]},
  "Hariyama": {"id": 297, "label": "铁掌力士", "abilities": ["Thick Fat", "Guts"]},
  "Azurill": {"id": 298, "label": "露力丽", "abilities": ["Thick Fat", "Huge Power"]},
  "Nosepass": {"id": 299, "label": "朝北鼻", "abilities": ["Sturdy", "Magnet Pull"]},
  "Skitty": {"id": 300, "label": "向尾喵", "abilities": ["Cute Charm"]},
  "Delcatty": {"id": 301, "label": "优雅猫", "abilities": ["Cute Charm"]},
  "Sableye": {"id": 302, "label": "勾魂眼", "abilities": ["Keen Eye"]},
  "Mawile": {"id": 303, "label": "大嘴娃", "abilities": ["Hyper Cutter", "Intimidate"]},
  "Aron": {"id": 304, "label": "可可多拉", "abilities": ["Sturdy", "Rock Head"]},
  "Lairon": {"id": 305, "label": "可多拉", "abilities": ["Sturdy", "Rock Head"]},
  "Aggron": {"id": 306, "label": "波士可多拉", "abilities": ["Sturdy", "Rock Head"]},
  "Meditite": {"id": 307, "label": "玛沙那", "abilities": ["Pure Power"]},
  "Medicham": {"id": 308, "label": "恰雷姆", "abilities": ["Pure Power"]},
  "Electrike": {"id": 309, "label": "落雷兽", "abilities": ["Static", "Lightning Rod"]},
  "Manectric": {"id": 310, "label": "雷电兽", "abilities": ["Static", "Lightning Rod"]},
  "Plusle": {"id": 311, "label": "正电拍拍", "abilities": ["Plus"]},
  "Minun": {"id": 312, "label": "负电拍拍", "abilities": ["Minus"]},
  "Volbeat": {"id": 313, "label": "电萤虫", "abilities": ["Illuminate", "Swarm"]},
  "Illumise": {"id": 314, "label": "甜甜萤", "abilities": ["Oblivious"]},
  "Roselia": {"id": 315, "label": "毒蔷薇", "abilities": ["Natural Cure", "Poison Point"]},
  "Gulpin": {"id": 316, "label": "溶食兽", "abilities": ["Liquid Ooze", "Sticky Hold"]},
  "Swalot": {"id": 317, "label": "吞食兽", "abilities": ["Liquid Ooze", "Sticky Hold"]},
  "Carvanha": {"id": 318, "label": "利牙鱼", "abilities": ["Rough Skin"]},
  "Sharpedo": {"id": 319, "label": "巨牙鲨", "abilities": ["Rough Skin"]},
  "Wailmer": {"id": 320, "label": "吼吼鲸", "abilities": ["Water Veil", "Oblivious"]},
  "Wailord": {"id": 321, "label": "吼鲸王", "abilities": ["Water Veil", "Oblivious"]},
  "Numel": {"id": 322, "label": "呆火驼", "abilities": ["Oblivious"]},
  "Camerupt": {"id": 323, "label": "喷火驼", "abilities": ["Magma Armor"]},
  "Torkoal": {"id": 324, "label": "煤炭龟", "abilities": ["White Smoke"]},
  "Spoink": {"id": 325, "label": "跳跳猪", "abilities": ["Thick Fat", "Own Tempo"]},
  "Grumpig": {"id": 326, "label": "噗噗猪", "abilities": ["Thick Fat", "Own Tempo"]},
  "Spinda": {"id": 327, "label": "晃晃斑", "abilities": ["Own Tempo"]},
  "Trapinch": {"id": 328, "label": "大颚蚁", "abilities": ["Hyper Cutter", "Arena Trap"]},
  "Vibrava": {"id": 329, "label": "超音波幼虫", "abilities": ["Levitate"]},
  "Flygon": {"id": 330, "label": "沙漠蜻蜓", "abilities": ["Levitate"]},
  "Cacnea": {"id": 331, "label": "刺球仙人掌", "abilities": ["Sand Veil"]},
  "Cacturne": {"id": 332, "label": "梦歌仙人掌", "abilities": ["Sand Veil"]},
  "Swablu": {"id": 333, "label": "青绵鸟", "abilities": ["Natural Cure"]},
  "Altaria": {"id": 334, "label": "七夕青鸟", "abilities": ["Natural Cure"]},
  "Zangoose": {"id": 335, "label": "猫鼬斩", "abilities": ["Immunity"]},
  "Seviper": {"id": 336, "label": "饭匙蛇", "abilities": ["Shed Skin"]},
  "Lunatone": {"id": 337, "label": "月石", "abilities": ["Levitate"]},
  "Solrock": {"id": 338, "label": "太阳岩", "abilities": ["Levitate"]},
  "Barboach": {"id": 339, "label": "泥泥鳅", "abilities": ["Oblivious"]},
  "Whiscash": {"id": 340, "label": "鲶鱼王", "abilities": ["Oblivious"]},
  "Corphish": {"id": 341, "label": "龙虾小兵", "abilities": ["Hyper Cutter", "Shell Armor"]},
  "Crawdaunt": {"id": 342, "label": "铁螯龙虾", "abilities": ["Hyper Cutter", "Shell Armor"]},
  "Baltoy": {"id": 343, "label": "天秤偶", "abilities": ["Levitate"]},
  "Claydol": {"id": 344, "label": "念力土偶", "abilities": ["Levitate"]},
  "Lileep": {"id": 345, "label": "触手百合", "abilities": ["Suction Cups"]},
  "Cradily": {"id": 346, "label": "摇篮百合", "abilities": ["Suction Cups"]},
  "Anorith": {"id": 347, "label": "太古羽虫", "abilities": ["Battle Armor"]},
  "Armaldo": {"id": 348, "label": "太古盔甲", "abilities": ["Battle Armor"]},
  "Feebas": {"id": 349, "label": "丑丑鱼", "abilities": ["Swift Swim"]},
  "Milotic": {"id": 350, "label": "美纳斯", "abilities": ["Marvel Scale"]},
  "Castform": {"id": 351, "label": "飘浮泡泡", "abilities": ["Forecast"]},
  "Kecleon": {"id": 352, "label": "变隐龙", "abilities": ["Color Change"]},
  "Shuppet": {"id": 353, "label": "怨影娃娃", "abilities": ["Insomnia"]},
  "Banette": {"id": 354, "label": "诅咒娃娃", "abilities": ["Insomnia"]},
  "Duskull": {"id": 355, "label": "夜巡灵", "abilities": ["Levitate"]},
  "Dusclops": {"id": 356, "label": "彷徨夜灵", "abilities": ["Pressure"]},
  "Tropius": {"id": 357, "label": "热带龙", "abilities": ["Chlorophyll"]},
  "Chimecho": {"id": 358, "label": "风铃铃", "abilities": ["Levitate"]},
  "Absol": {"id": 359, "label": "阿勃梭鲁", "abilities": ["Pressure"]},
  "Wynaut": {"id": 360, "label": "小果然", "abilities": ["Shadow Tag"]},
  "Snorunt": {"id": 361, "label": "雪童子", "abilities": ["Inner Focus"]},
  "Glalie": {"id": 362, "label": "冰鬼护", "abilities": ["Inner Focus"]},
  "Spheal": {"id": 363, "label": "海豹球", "abilities": ["Thick Fat"]},
  "Sealeo": {"id": 364, "label": "海魔狮", "abilities": ["Thick Fat"]},
  "Walrein": {"id": 365, "label": "帝牙海狮", "abilities": ["Thick Fat"]},
  "Clamperl": {"id": 366, "label": "珍珠贝", "abilities": ["Shell Armor"]},
  "Huntail": {"id": 367, "label": "猎斑鱼", "abilities": ["Swift Swim"]},
  "Gorebyss": {"id": 368, "label": "樱花鱼", "abilities": ["Swift Swim"]},
  "Relicanth": {"id": 369, "label": "古空棘鱼", "abilities": ["Swift Swim", "Rock Head"]},
  "Luvdisc": {"id": 370, "label": "爱心鱼", "abilities": ["Swift Swim"]},
  "Bagon": {"id": 371, "label": "宝贝龙", "abilities": ["Rock Head"]},
  "Shelgon": {"id": 372, "label": "甲壳龙", "abilities": ["Rock Head"]},
  "Salamence": {"id": 373, "label": "暴飞龙", "abilities": ["Intimidate"]},
  "Beldum": {"id": 374, "label": "铁哑铃", "abilities": ["Clear Body"]},
  "Metang": {"id": 375, "label": "金属怪", "abilities": ["Clear Body"]},
  "Metagross": {"id": 376, "label": "巨金怪", "abilities": ["Clear Body"]},
  "Regirock": {"id": 377, "label": "雷吉洛克", "abilities": ["Clear Body"]},
  "Regice": {"id": 378, "label": "雷吉艾斯", "abilities": ["Clear Body"]},
  "Registeel": {"id": 379, "label": "雷吉斯奇鲁", "abilities": ["Clear Body"]},
  "Latias": {"id": 380, "label": "拉帝亚斯", "abilities": ["Levitate"]},
  "Latios": {"id": 381, "label": "拉帝欧斯", "abilities": ["Levitate"]},
  "Kyogre": {"id": 382, "label": "盖欧卡", "abilities": ["Drizzle"]},
  "Groudon": {"id": 383, "label": "固拉多", "abilities": ["Drought"]},
  "Rayquaza": {"id": 384, "label": "烈空坐", "abilities": ["Air Lock"]},
  "Jirachi": {"id": 385, "label": "基拉祈", "abilities": ["Serene Grace"]},
  "Deoxys": {"id": 386, "label": "代欧奇希斯", "abilities": ["Pressure"]},
} as const;

export const FRLG_ABILITY_LABELS = {
  "Stench": "恶臭",
  "Drizzle": "降雨",
  "Speed Boost": "加速",
  "Battle Armor": "战斗盔甲",
  "Sturdy": "坚硬",
  "Damp": "湿气",
  "Limber": "柔软",
  "Sand Veil": "沙隐",
  "Static": "静电",
  "Volt Absorb": "蓄电",
  "Water Absorb": "储水",
  "Oblivious": "迟钝",
  "Cloud Nine": "无关天气",
  "Compound Eyes": "复眼",
  "Insomnia": "不眠",
  "Color Change": "变色",
  "Immunity": "免疫",
  "Flash Fire": "引火",
  "Shield Dust": "鳞粉",
  "Own Tempo": "我行我素",
  "Suction Cups": "吸盘",
  "Intimidate": "威吓",
  "Shadow Tag": "踩影",
  "Rough Skin": "粗糙皮肤",
  "Wonder Guard": "神奇守护",
  "Levitate": "飘浮",
  "Effect Spore": "孢子",
  "Synchronize": "同步",
  "Clear Body": "恒净之躯",
  "Natural Cure": "自然回复",
  "Lightning Rod": "避雷针",
  "Serene Grace": "天恩",
  "Swift Swim": "悠游自如",
  "Chlorophyll": "叶绿素",
  "Illuminate": "发光",
  "Trace": "复制",
  "Huge Power": "大力士",
  "Poison Point": "毒刺",
  "Inner Focus": "精神力",
  "Magma Armor": "熔岩铠甲",
  "Water Veil": "水幕",
  "Magnet Pull": "磁力",
  "Soundproof": "隔音",
  "Rain Dish": "雨盘",
  "Sand Stream": "扬沙",
  "Pressure": "压迫感",
  "Thick Fat": "厚脂肪",
  "Early Bird": "早起",
  "Flame Body": "火焰之躯",
  "Run Away": "逃跑",
  "Keen Eye": "锐利目光",
  "Hyper Cutter": "怪力钳",
  "Pickup": "捡拾",
  "Truant": "懒惰",
  "Hustle": "活力",
  "Cute Charm": "迷人之躯",
  "Plus": "正电",
  "Minus": "负电",
  "Forecast": "阴晴不定",
  "Sticky Hold": "黏着",
  "Shed Skin": "蜕皮",
  "Guts": "毅力",
  "Marvel Scale": "神奇鳞片",
  "Liquid Ooze": "污泥浆",
  "Overgrow": "茂盛",
  "Blaze": "猛火",
  "Torrent": "激流",
  "Swarm": "虫之预感",
  "Rock Head": "坚硬脑袋",
  "Drought": "日照",
  "Arena Trap": "沙穴",
  "Vital Spirit": "干劲",
  "White Smoke": "白烟",
  "Pure Power": "瑜伽之力",
  "Shell Armor": "硬壳盔甲",
  "Air Lock": "气闸",
} as const;

export const FRLG_NATURE_LABELS = {
  "Hardy": "勤奋",
  "Lonely": "怕寂寞",
  "Brave": "勇敢",
  "Adamant": "固执",
  "Naughty": "调皮",
  "Bold": "大胆",
  "Docile": "直率",
  "Relaxed": "悠闲",
  "Impish": "淘气",
  "Lax": "乐天",
  "Timid": "胆小",
  "Hasty": "急躁",
  "Serious": "认真",
  "Jolly": "爽朗",
  "Naive": "天真",
  "Modest": "内敛",
  "Mild": "慢吞吞",
  "Quiet": "冷静",
  "Bashful": "害羞",
  "Rash": "马虎",
  "Calm": "沉着",
  "Gentle": "温和",
  "Sassy": "自大",
  "Careful": "慎重",
  "Quirky": "浮躁",
  "Any": "不限",
} as const;

export const FRLG_TYPE_LABELS = {
  "Fighting": "格斗",
  "Flying": "飞行",
  "Poison": "毒",
  "Ground": "地面",
  "Rock": "岩石",
  "Bug": "虫",
  "Ghost": "幽灵",
  "Steel": "钢",
  "Fire": "火",
  "Water": "水",
  "Grass": "草",
  "Electric": "电",
  "Psychic": "超能力",
  "Ice": "冰",
  "Dragon": "龙",
  "Dark": "恶",
  "Any": "不限",
} as const;

export const FRLG_SOUND_LABELS = {
  "mono": "单声道",
  "stereo": "立体声",
} as const;

export const FRLG_BTN_MODE_LABELS = {
  "a": "L=A",
  "h": "帮助",
  "r": "LR",
} as const;

export const FRLG_SEED_BTN_LABELS = {
  "a": "A",
  "start": "开始",
  "l": "L (L=A)",
} as const;

export const FRLG_EXTRA_BTN_LABELS = {
  "none": "无",
  "startup_select": "启动时 Select",
  "startup_a": "启动时 A",
  "blackout_r": "黑屏后 R",
  "blackout_a": "黑屏后 A",
  "blackout_l": "黑屏后 L",
  "blackout_al": "黑屏后 A+L",
} as const;
